### ISSUE TITLE
Safe to use in production?

### ISSUE THREAD

**Issue by vvo** [defunctzombie/node-superstack#1]
Hello, node-superstack looks like a great module.

Is it reliable enough and safe to be used in a production system?

What are the risks?

**Comment by defunctzombie** [comment]
I've been using it in production for a while now (since I made it). The risks are that some api changes and for some reason the proxy calls don't work tho I think they all use `arguments` for the most part to avoid that.

As with any module, you should evaluate how critical your system is and try it in your testing environments first.

This module will introduce more function calls (overhead) but I think the benefit is worth it.

**Comment by vvo** [comment]
I did not have time to investigate further, but after setting up superstack in production
our RAM started to fill up quickly.

So our app is not compatible with superstack for now sadly.

I did not investigate further as we had a lot to do, we will certainly try again superstack in the near future and will debug our RAM issues when using it.

**Comment by defunctzombie** [comment]
@vvo I will keep this issue open. Let me know if you are able to track down the memory issue. I haven't seen it cause issues on my servers but don't monitor it that closely.
